En este notebook chequeo datos de la DB respecto a MCI->MCI y MCI->AD. Es decir, solo grupos que empiezan como MCI

In [1]:
import pandas as pd
import os
from os import path
import math
import numpy as np
import datetime

In [2]:
inputFile = 'ADNI-Full-PostProc/ADNI-FULL-PostProc_3_01_2023_UniformResolution.csv'
adniMergeCSV = '/Users/hugom/PET-IA/Data/ADNIMERGE.csv'
petMetaCSV = '/Users/hugom/PET-IA/Data/PET_META_LIST.csv'
csvDXSUMFile = '/Users/hugom/PET-IA/Data/DXSUM_PDXCONV_ADNIALL.csv'

In [3]:
csv = pd.read_csv(inputFile)
csv

,Image Data ID,Subject,Group,Sex,Age,Visit,Modality,Description,Type,Acq Date,Format,Downloaded
0,I1557047,941_S_7041,MCI,F,73,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,3/09/2022,DCM,11/29/2022
1,I1480671,941_S_6962,AD,F,75,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,8/10/2021,DCM,1/09/2023
2,I1301874,941_S_6854,AD,M,86,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,2/24/2020,DCM,12/02/2022
3,I1239316,941_S_6803,MCI,F,75,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,10/07/2019,DCM,11/28/2022
4,I1005488,941_S_6345,MCI,M,79,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,5/30/2018,DCM,11/29/2022
...,...,...,...,...,...,...,...,...,...,...,...,...
3757,I187801,002_S_0685,CN,F,94,m48,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,7/27/2010,DCM,11/28/2022
3758,I323915,002_S_0685,CN,F,96,v11,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,8/02/2012,DCM,12/02/2022
3759,I384689,002_S_0413,CN,F,83,v21,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,5/14/2013,DCM,11/28/2022
3760,I241476,002_S_0413,CN,F,82,v06,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,6/17/2011,DCM,11/29/2022
3761,I240519,002_S_0295,CN,M,90,v06,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,6/09/2011,DCM,12/02/2022

In [4]:
csvMci = csv[(csv['Group'] == 'MCI') | (csv['Group'] == 'EMCI') | (csv['Group'] == 'LMCI')]
csvMci

,Image Data ID,Subject,Group,Sex,Age,Visit,Modality,Description,Type,Acq Date,Format,Downloaded
0,I1557047,941_S_7041,MCI,F,73,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,3/09/2022,DCM,11/29/2022
3,I1239316,941_S_6803,MCI,F,75,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,10/07/2019,DCM,11/28/2022
4,I1005488,941_S_6345,MCI,M,79,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,5/30/2018,DCM,11/29/2022
5,I901584,941_S_6068,MCI,M,76,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,9/01/2017,DCM,11/29/2022
6,I882052,941_S_6052,MCI,F,88,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,7/24/2017,DCM,1/09/2023
...,...,...,...,...,...,...,...,...,...,...,...,...
3752,I209996,002_S_1155,MCI,M,62,m48,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,1/07/2011,DCM,1/09/2023
3753,I856314,002_S_1155,MCI,M,68,init,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,4/28/2017,DCM,12/02/2022
3754,I357451,002_S_1155,MCI,M,64,v11,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,1/03/2013,DCM,1/09/2023
3755,I324214,002_S_0729,MCI,F,71,v11,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,8/14/2012,DCM,11/29/2022
3756,I189823,002_S_0729,MCI,F,69,m48,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,7/29/2010,DCM,12/02/2022

In [96]:
csvMerge = pd.read_csv(adniMergeCSV,  dtype = {'DX' : str})

/var/folders/hy/rbnyh5md5yvc72ynxb0c2cz40000gn/T/ipykernel_18837/731607858.py:1: DtypeWarning: Columns (19,20,21,104,105,106) have mixed types. Specify dtype option on import or set low_memory=False.
  csvMerge = pd.read_csv(adniMergeCSV,  dtype = {'DX' : str})

In [97]:
# Eliminamos los que tengan DX = nan
csvMerge = csvMerge[csvMerge['DX'].notna() ]
len(csvMerge[csvMerge['DX'].isna()])

0

In [98]:
# Renombramos Dementia como AD
csvMerge.loc[csvMerge['DX'] == 'Dementia', 'DX'] = 'AD'

In [99]:
# "agrupamos por patient"
csvMergePerPatient = csvMerge.groupby(by='PTID').agg({'DX': list, 'VISCODE': list, 'EXAMDATE': [np.min, np.max]})

In [100]:
csvMergePerPatient['visits'] = csvMergePerPatient['DX'].applymap(lambda xs: len(xs))

In [101]:
# csvMergePerPatient['PTID'] = csvMergePerPatient.index
csvMergePerPatient = csvMergePerPatient.reset_index()
csvMergePerPatient

            PTID                                                 DX  \
                                                               list
0     002_S_0295                   [CN, CN, CN, CN, CN, CN, CN, CN]
1     002_S_0413  [CN, CN, CN, CN, CN, CN, CN, CN, CN, CN, CN, C...
2     002_S_0559                               [CN, CN, CN, CN, CN]
3     002_S_0619                                   [AD, AD, AD, AD]
4     002_S_0685                   [CN, CN, CN, CN, CN, CN, CN, CN]
...          ...                                                ...
2401  941_S_7041                                              [MCI]
2402  941_S_7046                                               [CN]
2403  941_S_7051                                               [CN]
2404  941_S_7074                                               [CN]
2405  941_S_7085                                              [MCI]

                                                VISCODE    EXAMDATE  \
                                                   list        amin
0               [bl, m06, m12, m24, m36, m48, m72, m60]  2006-05-09
1     [bl, m06, m12, m24, m36, m48, m108, m96, m84, ...  2006-05-08
2                              [bl, m24, m36, m06, m12]  2006-06-20
3                                   [bl, m06, m12, m24]  2006-06-20
4               [bl, m06, m12, m24, m36, m48, m60, m72]  2006-07-20
...                                                 ...         ...
2401                                               [bl]  2022-03-01
2402                                               [bl]  2022-04-06
2403                                               [bl]  2022-03-30
2404                                               [bl]  2022-05-02
2405                                               [bl]  2022-07-11

                 visits
            amax
0     2012-05-10      8
1     2019-08-22     13
2     2009-07-02      5
3     2008-08-07      4
4     2012-07-27      8
...          ...    ...
2401  2022-03-01      1
2402  2022-04-06      1
2403  2022-03-30      1
2404  2022-05-02      1
2405  2022-07-11      1

[2406 rows x 6 columns]

In [102]:
# Avoiding multi index to avoid pain
csvMergePerPatient.columns = ['PTID', 'DX', 'VISCODE', 'EXAMDATE_min', 'EXAMDATE_max', 'visits']

In [103]:
csvMergePerPatient['DX_last'] = csvMergePerPatient['DX'].apply(lambda xs: xs[-1])

In [104]:
csvMergePerPatient.groupby(by='DX_last').describe()

        visits
         count      mean       std  min   25%  50%  75%   max
DX_last
AD       681.0  4.687225  2.834239  1.0  3.00  4.0  6.0  16.0
CN       851.0  4.412456  3.138420  1.0  2.00  4.0  6.0  16.0
MCI      874.0  5.090389  3.247320  1.0  2.25  5.0  7.0  18.0

In [105]:
# Devuelve el diagnÃ³stico mas severo de una lista de diagnÃ³sticos
def dxGetMostSevere(xs):
    mostSevere = 'CN'
    for x in xs:
        if x == 'MCI' and mostSevere == 'CN':
            mostSevere = 'MCI'
        if x == 'AD':
            mostSevere = 'AD'
    return mostSevere

csvMergePerPatient['DX_most_severe'] = csvMergePerPatient['DX'].apply(dxGetMostSevere)

In [106]:
csvMergePerPatient.groupby(by='DX_most_severe').describe()

               visits
                count      mean       std  min  25%  50%  75%   max
DX_most_severe
AD              825.0  4.983030  2.867156  1.0  3.0  4.0  6.0  16.0
CN              746.0  4.032172  2.933543  1.0  2.0  3.0  5.0  14.0
MCI             835.0  5.122156  3.377088  1.0  2.0  5.0  7.0  18.0

In [107]:
fullMerge = pd.merge(
    csvMci,
    csvMergePerPatient, # Nos quedamos solo con las columnas de interÃ©s
    how="inner",
    on=None,
    left_on='Subject',
    right_on='PTID',
    left_index=False,
    right_index=False,
    sort=True,
    suffixes=("_x", "_y"),
    copy=True,
    indicator=False,
    validate=None,
)

In [108]:
fullMerge

,Image Data ID,Subject,Group,Sex,Age,Visit,Modality,Description,Type,Acq Date,Format,Downloaded,PTID,DX,VISCODE,EXAMDATE_min,EXAMDATE_max,visits,DX_last,DX_most_severe
0,I324214,002_S_0729,MCI,F,71,v11,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,8/14/2012,DCM,11/29/2022,002_S_0729,"[MCI, MCI, AD, AD, AD, AD, AD, AD, AD, AD]","[bl, m06, m12, m36, m18, m24, m48, m84, m72, m60]",2006-08-02,2013-08-08,10,AD,AD
1,I189823,002_S_0729,MCI,F,69,m48,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,7/29/2010,DCM,12/02/2022,002_S_0729,"[MCI, MCI, AD, AD, AD, AD, AD, AD, AD, AD]","[bl, m06, m12, m36, m18, m24, m48, m84, m72, m60]",2006-08-02,2013-08-08,10,AD,AD
2,I209996,002_S_1155,MCI,M,62,m48,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,1/07/2011,DCM,1/09/2023,002_S_1155,"[MCI, MCI, MCI, MCI, MCI, MCI, MCI, MCI, MCI, ...","[m06, m12, m18, m24, m48, m36, bl, m108, m96, ...",2007-01-04,2019-05-13,15,MCI,MCI
3,I856314,002_S_1155,MCI,M,68,init,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,4/28/2017,DCM,12/02/2022,002_S_1155,"[MCI, MCI, MCI, MCI, MCI, MCI, MCI, MCI, MCI, ...","[m06, m12, m18, m24, m48, m36, bl, m108, m96, ...",2007-01-04,2019-05-13,15,MCI,MCI
4,I357451,002_S_1155,MCI,M,64,v11,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,1/03/2013,DCM,1/09/2023,002_S_1155,"[MCI, MCI, MCI, MCI, MCI, MCI, MCI, MCI, MCI, ...","[m06, m12, m18, m24, m48, m36, bl, m108, m96, ...",2007-01-04,2019-05-13,15,MCI,MCI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2132,I882052,941_S_6052,MCI,F,88,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,7/24/2017,DCM,1/09/2023,941_S_6052,"[MCI, MCI]","[bl, m12]",2017-07-28,2018-07-02,2,MCI,MCI
2133,I901584,941_S_6068,MCI,M,76,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,9/01/2017,DCM,11/29/2022,941_S_6068,"[MCI, MCI, MCI, AD, AD]","[bl, m12, m24, m48, m60]",2017-08-30,2022-08-16,5,AD,AD
2134,I1005488,941_S_6345,MCI,M,79,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,5/30/2018,DCM,11/29/2022,941_S_6345,"[MCI, AD, AD]","[bl, m12, m30]",2018-05-14,2020-08-31,3,AD,AD
2135,I1239316,941_S_6803,MCI,F,75,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,10/07/2019,DCM,11/28/2022,941_S_6803,[MCI],[bl],2019-09-17,2019-09-17,1,MCI,MCI
2136,I1557047,941_S_7041,MCI,F,73,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,3/09/2022,DCM,11/29/2022,941_S_7041,[MCI],[bl],2022-03-01,2022-03-01,1,MCI,MCI

In [112]:
fullMerge[fullMerge['DX_last'] != fullMerge['DX_most_severe']]

,Image Data ID,Subject,Group,Sex,Age,Visit,Modality,Description,Type,Acq Date,Format,Downloaded,PTID,DX,VISCODE,EXAMDATE_min,EXAMDATE_max,visits,DX_last,DX_most_severe
5,I364744,002_S_1268,MCI,M,89,v11,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,3/26/2013,DCM,1/09/2023,002_S_1268,"[MCI, MCI, MCI, MCI, MCI, MCI, MCI, AD, MCI]","[m06, m12, m18, m24, m36, m48, bl, m72, m60]",2007-03-07,2013-03-14,9,MCI,AD
6,I228536,002_S_1268,MCI,M,87,m48,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,4/19/2011,DCM,11/29/2022,002_S_1268,"[MCI, MCI, MCI, MCI, MCI, MCI, MCI, AD, MCI]","[m06, m12, m18, m24, m36, m48, bl, m72, m60]",2007-03-07,2013-03-14,9,MCI,AD
7,I187065,002_S_2010,EMCI,F,63,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,7/14/2010,DCM,12/02/2022,002_S_2010,"[MCI, CN, CN, CN, CN, CN]","[bl, m06, m12, m24, m36, m60]",2010-07-08,2015-07-14,6,CN,MCI
8,I318309,002_S_2010,EMCI,F,65,v11,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,7/12/2012,DCM,12/02/2022,002_S_2010,"[MCI, CN, CN, CN, CN, CN]","[bl, m06, m12, m24, m36, m60]",2010-07-08,2015-07-14,6,CN,MCI
12,I415352,002_S_4171,LMCI,M,72,v21,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,10/29/2013,DCM,12/02/2022,002_S_4171,"[AD, MCI, MCI, MCI]","[m24, m12, m06, bl]",2011-08-25,2013-10-29,4,MCI,AD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2058,I285756,141_S_4426,LMCI,M,77,v03,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,2/17/2012,DCM,11/29/2022,141_S_4426,"[MCI, AD, MCI, MCI, MCI]","[m36, m24, m12, m06, bl]",2012-01-30,2015-03-09,5,MCI,AD
2100,I998038,301_S_6297,MCI,M,82,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,5/14/2018,DCM,12/02/2022,301_S_6297,"[MCI, MCI, MCI, CN]","[bl, m12, m24, m36]",2018-05-02,2021-04-12,4,CN,MCI
2109,I1326837,305_S_6871,MCI,F,68,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,6/29/2020,DCM,1/09/2023,305_S_6871,"[MCI, MCI, CN]","[bl, m12, m24]",2020-06-26,2022-07-13,3,CN,MCI
2127,I398641,941_S_4187,LMCI,M,64,v21,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,9/11/2013,DCM,12/02/2022,941_S_4187,"[MCI, MCI, MCI, MCI, MCI, MCI, CN, CN, CN, CN,...","[m48, m36, m24, m12, m06, bl, m120, m72, m96, ...",2011-08-25,2022-10-04,11,CN,MCI
2128,I255208,941_S_4187,LMCI,M,62,v03,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,9/02/2011,DCM,11/28/2022,941_S_4187,"[MCI, MCI, MCI, MCI, MCI, MCI, CN, CN, CN, CN,...","[m48, m36, m24, m12, m06, bl, m120, m72, m96, ...",2011-08-25,2022-10-04,11,CN,MCI

In [115]:
len(fullMerge[fullMerge['DX_last'] != fullMerge['DX_most_severe']])

409

In [109]:
fullMerge.groupby(by='DX_last').describe()

            Age                                                     visits  \
          count       mean       std   min   25%   50%   75%   max   count
DX_last
AD        664.0  75.962349  7.147662  55.0  72.0  76.0  81.0  96.0   664.0
CN        146.0  69.534247  7.624068  55.0  64.0  67.0  73.0  94.0   146.0
MCI      1327.0  74.954785  7.799006  55.0  70.0  75.0  81.0  94.0  1327.0


             mean       std  min  25%  50%   75%   max
DX_last
AD       7.945783  2.861838  2.0  6.0  7.0  10.0  15.0
CN       8.431507  3.594838  2.0  6.0  8.0  10.0  16.0
MCI      6.446873  3.467801  1.0  4.0  6.0   9.0  18.0

In [110]:
fullMerge.groupby(by='DX_most_severe').describe()

                   Age                                                     \
                 count       mean       std   min   25%   50%   75%   max
DX_most_severe
AD               929.0  75.862217  7.246013  55.0  71.0  76.0  81.0  96.0
CN                 2.0  65.000000  1.414214  64.0  64.5  65.0  65.5  66.0
MCI             1206.0  74.170813  8.019003  55.0  68.0  74.0  80.0  94.0

                visits
                 count      mean       std  min  25%  50%   75%   max
DX_most_severe
AD               929.0  7.699677  2.831323  2.0  6.0  7.0  10.0  15.0
CN                 2.0  8.000000  0.000000  8.0  8.0  8.0   8.0   8.0
MCI             1206.0  6.544776  3.689514  1.0  4.0  6.0   9.0  18.0

In [113]:
fullMerge[fullMerge['DX_most_severe'] == 'CN']

,Image Data ID,Subject,Group,Sex,Age,Visit,Modality,Description,Type,Acq Date,Format,Downloaded,PTID,DX,VISCODE,EXAMDATE_min,EXAMDATE_max,visits,DX_last,DX_most_severe
1347,I216342,094_S_2201,EMCI,F,64,bl,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,2/03/2011,DCM,11/28/2022,094_S_2201,"[CN, CN, CN, CN, CN, CN, CN, CN]","[bl, m06, m12, m24, m36, m48, m60, m78]",2011-01-24,2017-10-04,8,CN,CN
1348,I355034,094_S_2201,EMCI,F,66,v11,PET,"Coreg, Avg, Std Img and Vox Siz, Uniform Resol...",Processed,1/08/2013,DCM,1/09/2023,094_S_2201,"[CN, CN, CN, CN, CN, CN, CN, CN]","[bl, m06, m12, m24, m36, m48, m60, m78]",2011-01-24,2017-10-04,8,CN,CN

Lo de arriba indica algo raro en la data, deberÃ­a revisarse?

In [111]:
fullMerge.groupby(by='visits').describe()

          Age
        count       mean       std   min    25%   50%    75%   max
visits
1        84.0  72.035714  7.117679  56.0  67.75  73.0  77.00  88.0
2        98.0  73.653061  7.494468  56.0  68.00  74.0  78.75  90.0
3       116.0  74.465517  7.916335  56.0  70.00  73.5  79.25  90.0
4       159.0  74.295597  7.937695  56.0  69.00  75.0  80.00  94.0
5       220.0  75.454545  7.216972  56.0  71.00  77.0  80.00  92.0
6       406.0  75.357143  8.019916  55.0  69.00  75.0  82.00  90.0
7       284.0  75.644366  7.145406  56.0  72.00  76.0  81.00  91.0
8       109.0  71.899083  6.950813  59.0  66.00  72.0  77.00  88.0
9       155.0  76.458065  7.766260  58.0  71.00  75.0  83.00  94.0
10      155.0  75.432258  7.893791  55.0  69.00  76.0  82.00  90.0
11      110.0  72.381818  8.175800  55.0  67.00  73.0  78.00  91.0
12       71.0  76.732394  6.615907  64.0  73.00  76.0  81.50  91.0
13       82.0  76.280488  8.865628  57.0  70.00  76.5  81.00  96.0
14       34.0  78.235294  7.177654  67.0  72.00  79.0  84.00  92.0
15       27.0  74.666667  5.837544  62.0  71.00  73.0  80.00  84.0
16       14.0  65.857143  1.875229  63.0  65.00  65.5  66.75  70.0
17       10.0  80.400000  3.339993  77.0  78.00  79.5  82.50  87.0
18        3.0  70.333333  3.511885  67.0  68.50  70.0  72.00  74.0

In [123]:
fullMerge['visits'].describe()

count    2137.000000
mean        7.048198
std         3.389787
min         1.000000
25%         5.000000
50%         6.000000
75%         9.000000
max        18.000000
Name: visits, dtype: float64