Crea el set Fleni600 80/10/10 (aprox), donde el set de test será Fleni60.

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Fleni600_90_10

In [3]:
outputTrainFile = '../Sets/fleni600_90_10_train.csv'
outputValFile = '../Sets/fleni600_90_10_val.csv'

In [4]:
csvFile = '../Sets/fleni600_limpio.csv'
csv = pd.read_csv(csvFile)

In [5]:
csv

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,StudyDate,anon_id,PatientID,PatientSex,PatientName,Conclusion,Diagnóstico
0,0,0,238,20200825,625ddb3f-6b6adb4a-0653c1b1-1e566cc8-3fe2fab5,702774,M,WANGER^WALTER ROBERTO,-ALa distribución espacial de los hallazgos ...,AD
1,1,1,234,20201006,c45568f2-c860c13b-ddabe3eb-7bc72f65-dc96ba33,701575,F,RUBIO^MARIA ALEJANDRA,-ALa distribución espacial de los hallazgos ...,AD
2,2,2,435,20190426,b0e1b100-f29d020b-07fb9c16-bb41abdc-43d7b0e8,597445,F,BRALO^ALICIA ESTER,-ALa distribución espacial de los hallazgos ...,AD
3,3,3,247,20200804,ee1769c5-189b12d7-187a454e-f13189f4-19f82052,554900,M,LOBOS^ANIBAL PEDRO,Amiloidosis cortical difusa en el presente e...,AD
4,4,4,387,20190718,ec84b311-4f89bd80-bfd691ed-bb1cd2f4-c700b95c,655037,F,SANCHEZ^MARCELA ADRIANA,Amiloidosis cortical difusa en el presente e...,AD
...,...,...,...,...,...,...,...,...,...,...
624,633,633,165,20210923,55e4e05f-63d7f972-8268b162-88e10c2f-b357b9d5,716430,M,ANTOLIN^ELEODORO JORGE,"La ausencia de PIB en corteza cerebral, al mo...",non-AD
625,634,634,167,20210920,3e933062-0cb72fab-bcea413b-79beaa2d-f216915e,735946,F,LEJTMAN^BERTA LILIANA,"La ausencia de PIB en corteza cerebral, al mo...",non-AD
626,635,635,205,20210111,e8c79ba5-6d9dbbda-ee35f81a-fb297bc9-bd605906,702579,M,PARDO^SILVERIO,"La ausencia de PIB en corteza cerebral, al mo...",non-AD
627,636,636,926,20150915,efbf3dab-14c5c80e-55f0f93d-482237a0-9acc8e1f,212192,M,SACK^AUGUSTO,La ausencia de retención de amiloide disminuy...,non-AD
628,637,637,951,20150915,7fb34c5b-122c2b29-27c260a3-d6351b3c-ffddfa6c,212192,M,SACK^AUGUSTO,La ausencia de retención de amiloide disminuy...,non-AD

In [51]:
csv.groupby(['PatientSex', "Diagnóstico"]).describe()

                       Unnamed: 0.2                                        \
                              count        mean        std    min     25%
PatientSex Diagnóstico
F          AD                 186.0  159.645161  99.215315    1.0   79.50
           non-AD             126.0  493.841270  80.696807  348.0  423.00
M          AD                 151.0  181.735099  97.464161    0.0   99.50
           non-AD             166.0  487.777108  88.982898  341.0  416.25

                                             Unnamed: 0.1              ...  \
                          50%     75%    max        count        mean  ...
PatientSex Diagnóstico                                                 ...
F          AD           148.0  243.75  340.0        186.0  159.645161  ...
           non-AD       491.5  566.50  634.0        126.0  493.841270  ...
M          AD           191.0  266.50  337.0        151.0  181.735099  ...
           non-AD       488.5  563.75  637.0        166.0  487.777108  ...

                          StudyDate             PatientID                 \
                                75%         max     count           mean
PatientSex Diagnóstico
F          AD           20200217.75  20221216.0     186.0  586017.064516
           non-AD       20200187.25  20230105.0     126.0  505647.142857
M          AD           20201210.00  20221216.0     151.0  540644.476821
           non-AD       20191228.25  20221229.0     166.0  546020.210843

                                                                     \
                                  std      min        25%       50%
PatientSex Diagnóstico
F          AD           149273.196458   7895.0  545922.00  612069.5
           non-AD       204379.655457  24660.0  426144.25  554616.0
M          AD           190972.569159  55649.0  504083.50  592670.0
           non-AD       186171.993811   5746.0  525229.25  597370.5


                              75%       max
PatientSex Diagnóstico
F          AD           673043.00  778373.0
           non-AD       646612.25  773353.0
M          AD           676249.00  774615.0
           non-AD       667898.75  771613.0

[4 rows x 40 columns]

Removemos Fleni60

In [26]:
fleni60File = '../Sets/fleni-PET_clasificados60.csv'
fleni60 = pd.read_csv(fleni60File)

In [27]:
fleni60

,StudyDate,anon_id,PatientSex,Unnamed: 3,Conclusion PET
0,20221227,44a28d4d-715fb1d1-a27b6b74-8453221e-971636d2,M,NaN,AD
1,20220221,bed8e34e-9cce115f-41d35acb-2299c2d0-5c1eda47,M,NaN,AD
2,20220419,92a4e09d-f3b1bf4b-400c048c-9e0da253-522144d4,M,NaN,AD
3,20221027,d3e65f9f-b900bf1c-20711c1d-3c1a2020-b1c08e1d,M,NaN,AD
4,20221031,ed140931-163cd49b-c10b164f-f5be07d3-9fdd9020,M,NaN,AD
5,20220811,e8c3e0b2-5bc7ec78-36df4fdd-1fd16c31-2de77b5e,F,NaN,AD
6,20220908,60afec12-08579f16-432289de-c3a1600c-06562055,F,NaN,AD
7,20220707,74cbd572-0a9978dc-25e1ee27-d0291523-a9c6a8b4,F,NaN,AD
8,20220707,838b6ced-3e6f25b6-b8799a71-9ab43e5b-ffe8776d,F,NaN,AD
9,20220414,164751e1-d6db08f6-8eea8b79-a2ef609c-362a8321,M,NaN,AD
10,20220509,898776ca-aef78c5e-e93b96c9-8d4b730b-409da4cf,F,NaN,AD
11,20220210,20f18c9a-94af6cfb-41c15927-301a50bb-6574e5b3,F,NaN,AD
12,20220218,ed9da20f-0ffdf438-8431ae58-e0f365b8-1c2c968c,M,NaN,AD
13,20220613,a2a42680-e0608ab1-2a69fe41-032598e6-1b350022,M,NaN,AD
14,20220616,18cd0ce6-a2a728e1-6db1f358-8f85eba2-395d1521,M,NaN,AD
15,20220506,dbdcefa2-d37077db-8e21c368-f4fc53a9-16e4751b,F,NaN,AD
16,20220419,2db1aabf-bdfd1f90-4bb0ffc1-1a8abf80-742a68d8,M,NaN,AD
17,20221018,c5a816aa-9ebed134-583b8cb6-d312d63c-e763b44c,M,NaN,AD
18,20221216,6d955f3c-d72106fa-9acfcafa-9788d41b-95a19124,M,NaN,AD
19,20221216,6679c9ac-ff5b3eee-73520f1e-adf11e7d-4d331dfe,F,NaN,AD
20,20221031,802936ff-1599b220-dea72077-b0a7e85d-d320d005,F,NaN,AD
21,20221021,4d3647c4-ec43e4da-9ac736e1-93f4e3f4-ad1ff84e,M,NaN,AD
22,20220809,3aa18eb0-43ae540c-ca30594d-3b2cc125-5028af82,M,NaN,AD
23,20220422,76e55c22-e7e28d2d-284653a6-24b0857d-7dcb4e8b,F,NaN,AD
24,20221101,4efd6bdc-78538dc7-3500a241-68a8cd25-def9359c,M,NaN,AD
25,20221215,82b4b3ea-c93d9b9f-671d1811-06bf0e60-f1a245ab,F,NaN,AD
26,20221213,799e2454-cb073f25-e4d89d32-6d5f68f6-2275c41a,F,NaN,AD
27,20221215,87bdd35c-7a483a1a-494d870f-9806c98d-9b1836db,F,NaN,AD
28,20221013,c14b470d-8202d4ab-8e1b6196-528c0758-2436801d,M,NaN,AD
29,20221014,6b5b8a5e-035ae6be-897921bd-791d2d2c-d98b5c13,F,NaN,AD
30,20221014,267b86fb-64c2754d-00020126-60d16ff0-98efe3ff,F,NaN,AD
31,20220429,23698a3b-71e234ac-db7ced18-262c0eee-bef83ae8,M,NaN,AD
32,20220310,c110f580-15e17672-c7019cde-808d96be-71605933,M,NaN,AD
33,20220217,ab47140f-baad2159-96f435e7-8e4c9f49-7b76fa01,M,NaN,AD
34,20220614,86e09b2a-964f1e72-f5e48129-240d3885-fddaea1d,M,NaN,AD
35,20220422,aab7877d-3e1e3fbd-2c6b4179-7c1e3cba-c69fab29,F,NaN,AD
36,20220502,b53f2231-3afbe9e0-f2b2b3b3-913feef9-d4a416b0,M,NaN,AD
37,20221011,a393e3fa-56095165-eb554350-cf744b58-ca5028e0,F,NaN,AD
38,20220616,f34fd8af-c1044ddc-6d2bd6aa-77732cd4-462e6c8e,F,NaN,AD
39,20221102,7aaf5d60-b100d546-73de9f0c-e3ce2f34-d299d6a5,F,NaN,non-AD
40,20220810,756ba54b-a50b1dd7-b8a1460a-69a5f0f0-601bd0fb,F,NaN,non-AD
41,20220907,c27c9d7d-1d6e603f-dfcea933-42beb746-e53f326c,F,NaN,non-AD
42,20220809,7562bd21-e117f2f5-a9e06568-6b4e3b2f-4629a8ef,F,NaN,non-AD
43,20220629,bb1647b2-6168d5ea-3939f6fa-167b41ea-fa0575d8,F,NaN,non-AD
44,20220628,59e3780a-8ba7d428-49b50ddd-3aed7c74-fb51d15b,F,NaN,non-AD
45,20220628,7b2563e2-796b12c0-5ca8a153-17618566-6da77739,F,NaN,non-AD
46,20220622,45fe81a7-51af4a29-0aaa99dd-98d06794-4e0f96d2,M,NaN,non-AD
47,20220622,2183eb4f-e8b3a7b3-9488841c-c974e2c0-82c43246,M,NaN,non-AD
48,20220706,edbeaaf6-3063cc63-422dd81c-aa3f610e-401f880d,M,NaN,non-AD
49,20221220,df197ff2-850f98d6-b2387220-e73af43c-4608190c,M,NaN,non-AD
50,20221216,836a6184-3d59edfe-c0d953b9-c9ac24c3-c6202b3f,F,NaN,non-AD
51,20221215,1601430e-86bbe761-b9509c4b-7a8e6d99-b909e67d,M,NaN,non-AD
52,20230105,7a53db60-4103fd5a-b239b692-e2ed450a-165fe39b,M,NaN,non-AD
53,20220812,557a799c-be501c9c-64c80ca1-2beffbe8-cd4a697e,F,NaN,non-AD
54,20220707,10490022-d27d7764-f384f071-2e0cdfc9-6e94d416,F,NaN,non-AD
55,20220810,f5491bc8-aff8bd50-262b248e-fa7a8fbc-21650cf5,M,NaN,non-AD
56,20221025,850ea59a-596bd866-9ccf7153-04c81697-66e227d5,M,NaN,non-AD
57,20221229,8a18dca8-3e89b5c1-0be97cc9-d7f8341e-85841d4b,M,NaN,non-AD
58,20220817,84168646-e1596a6e-c0f29869-cb365242-5f4c77d6,M,NaN,non-AD
59,20221229,3d2e40b7-821f88a4-3c34f1e4-ed322a47-6aca39e2,M,NaN,non-AD

Removemos Fleni60 de Fleni600

In [32]:
len(fleni60['anon_id'].unique())

60

In [34]:
len(csv[csv['anon_id'].isin(fleni60['anon_id'])])

36

Raro, solo hay 36 rows en fleni600 que corresponden a fleni60... habría que probar quizás con el archivo original

In [36]:
orig = '../Sets/fleni600_original.csv'
csvOrig = pd.read_csv(csvFile)
len(csvOrig[csvOrig['anon_id'].isin(fleni60['anon_id'])])

36

También... raro. TODO: preguntar

In [37]:
csv = csv.drop(csv[csv['anon_id'].isin(fleni60['anon_id'])].index)
len(csv)

593

In [38]:
train, val = train_test_split(csv, test_size = 0.1, stratify=csv["Diagnóstico"], random_state = 222)

In [39]:
len(train)

533

In [40]:
len(val)

60

In [41]:
train.to_csv(outputTrainFile)
val.to_csv(outputValFile)

In [43]:
train.groupby('Diagnóstico').describe()

            Unnamed: 0.2                                                \
                   count        mean         std    min     25%    50%
Diagnóstico
AD                 271.0  161.099631  100.691982    0.0   74.50  156.0
non-AD             262.0  491.725191   86.411433  341.0  418.25  492.5

                           Unnamed: 0.1              ...    StudyDate  \
                75%    max        count        mean  ...          75%
Diagnóstico                                          ...
AD           242.00  340.0        271.0  161.099631  ...  20191164.50
non-AD       568.75  637.0        262.0  491.725191  ...  20200116.75

                        PatientID                                         \
                    max     count           mean            std      min
Diagnóstico
AD           20220307.0     271.0  560683.907749  162682.726710  45914.0
non-AD       20230105.0     262.0  525386.045802  198606.186591   5746.0


                  25%       50%       75%       max
Diagnóstico
AD           534938.0  600366.0  665869.5  750738.0
non-AD       467797.0  583949.0  665632.5  773353.0

[2 rows x 40 columns]

In [46]:
fleni60.groupby('Conclusion PET').describe()

               StudyDate                                                     \
                   count          mean          std         min         25%
Conclusion PET
AD                  39.0  2.022075e+07   338.687207  20220210.0  20220425.5
non-AD              21.0  2.022133e+07  2024.644929  20220622.0  20220706.0

                                                   Unnamed: 3               \
                       50%         75%         max      count mean std min
Conclusion PET
AD              20220707.0  20221024.0  20221227.0        0.0  NaN NaN NaN
non-AD          20220812.0  20221215.0  20230105.0        0.0  NaN NaN NaN


               25% 50% 75% max
Conclusion PET
AD             NaN NaN NaN NaN
non-AD         NaN NaN NaN NaN

# Fleni600_80_10_10

In [6]:
outputTrainFile = '../Sets/fleni600_80_10_10_train.csv'
outputValFile = '../Sets/fleni600_80_10_10_val.csv'
outputTestFile = '../Sets/fleni600_80_10_10_test.csv'

En este caso NO removemos Fleni60, ya que no nos importa porque no lo usaremos como set de test.

In [7]:
train, tail = train_test_split(csv, test_size = 0.2, stratify=csv["Diagnóstico"], random_state = 222)

In [8]:
val, test  = train_test_split(tail, test_size = 0.5, stratify=tail["Diagnóstico"], random_state = 222)

In [9]:
train.groupby('Diagnóstico').describe()

            Unnamed: 0.2                                                       \
                   count        mean        std    min     25%    50%     75%
Diagnóstico
AD                 269.0  170.940520  98.172690    0.0   88.00  174.0  254.00
non-AD             234.0  488.782051  86.286624  341.0  413.25  483.5  566.75

                   Unnamed: 0.1              ...   StudyDate              \
               max        count        mean  ...         75%         max
Diagnóstico                                  ...
AD           340.0        269.0  170.940520  ...  20201026.0  20221216.0
non-AD       637.0        234.0  488.782051  ...  20200120.0  20230105.0

            PatientID                                                    \
                count           mean            std      min        25%
Diagnóstico
AD              269.0  569768.070632  164478.447993  55649.0  537418.00
non-AD          234.0  531059.893162  196094.534625   5746.0  477230.25


                  50%       75%       max
Diagnóstico
AD           605217.0  675784.0  778373.0
non-AD       583340.0  667659.5  773353.0

[2 rows x 40 columns]

In [10]:
train.groupby(['PatientSex', 'Diagnóstico']).describe()

                       Unnamed: 0.2                                        \
                              count        mean        std    min     25%
PatientSex Diagnóstico
F          AD                 149.0  162.838926  99.812802    1.0   82.00
           non-AD             100.0  495.630000  81.614350  364.0  419.75
M          AD                 120.0  181.000000  95.555167    0.0  105.75
           non-AD             134.0  483.671642  89.575253  341.0  411.00

                                            Unnamed: 0.1              ...  \
                          50%    75%    max        count        mean  ...
PatientSex Diagnóstico                                                ...
F          AD           157.0  250.0  340.0        149.0  162.838926  ...
           non-AD       488.5  578.5  634.0        100.0  495.630000  ...
M          AD           188.0  260.0  337.0        120.0  181.000000  ...
           non-AD       479.5  554.5  637.0        134.0  483.671642  ...

                          StudyDate             PatientID                 \
                                75%         max     count           mean
PatientSex Diagnóstico
F          AD           20201006.00  20221216.0     149.0  599147.496644
           non-AD       20200207.25  20230105.0     100.0  496468.370000
M          AD           20201116.00  20221216.0     120.0  533288.616667
           non-AD       20191223.00  20221101.0     134.0  556874.462687

                                                                     \
                                  std      min        25%       50%
PatientSex Diagnóstico
F          AD           126631.264084  95469.0  552381.00  617677.0
           non-AD       207577.235299  27742.0  395278.75  551813.5
M          AD           196368.216994  55649.0  483233.25  593716.5
           non-AD       183632.275336   5746.0  533689.25  607365.0


                              75%       max
PatientSex Diagnóstico
F          AD           674842.00  778373.0
           non-AD       644272.75  773353.0
M          AD           676016.50  774615.0
           non-AD       675401.00  771613.0

[4 rows x 40 columns]

In [11]:
val.groupby('Diagnóstico').describe()

            Unnamed: 0.2                                                \
                   count        mean         std    min     25%    50%
Diagnóstico
AD                  34.0  160.382353  108.791994    4.0   66.25  138.0
non-AD              29.0  495.965517   79.940372  349.0  442.00  495.0

                           Unnamed: 0.1              ...    StudyDate  \
                75%    max        count        mean  ...          75%
Diagnóstico                                          ...
AD           254.25  331.0         34.0  160.382353  ...  20205386.25
non-AD       548.00  626.0         29.0  495.965517  ...  20210212.00

                        PatientID                                         \
                    max     count           mean            std      min
Diagnóstico
AD           20221021.0      34.0  581748.411765  145541.677863  29393.0
non-AD       20221229.0      29.0  528941.000000  197752.673640  24660.0


                  25%       50%        75%       max
Diagnóstico
AD           540804.0  603175.5  663634.75  755759.0
non-AD       519437.0  601274.0  634166.00  760661.0

[2 rows x 40 columns]

In [12]:
val.groupby(['PatientSex', 'Diagnóstico']).describe()

                       Unnamed: 0.2                                         \
                              count        mean         std    min     25%
PatientSex Diagnóstico
F          AD                  16.0  134.000000  103.675134    4.0   65.50
           non-AD              12.0  501.333333   84.480588  349.0  463.25
M          AD                  18.0  183.833333  110.696857   34.0   72.25
           non-AD              17.0  492.176471   78.992274  371.0  440.00

                                             Unnamed: 0.1              ...  \
                          50%     75%    max        count        mean  ...
PatientSex Diagnóstico                                                 ...
F          AD           112.0  178.00  317.0         16.0  134.000000  ...
           non-AD       523.5  551.50  626.0         12.0  501.333333  ...
M          AD           219.0  269.25  331.0         18.0  183.833333  ...
           non-AD       488.0  542.00  620.0         17.0  492.176471  ...

                          StudyDate             PatientID                 \
                                75%         max     count           mean
PatientSex Diagnóstico
F          AD           20190499.00  20220509.0      16.0  588425.562500
           non-AD       20202883.75  20220812.0      12.0  546809.833333
M          AD           20210889.00  20221021.0      18.0  575813.166667
           non-AD       20210212.00  20221229.0      17.0  516327.705882

                                                                      \
                                  std       min        25%       50%
PatientSex Diagnóstico
F          AD           161524.418498   29393.0  570001.25  620693.0
           non-AD       216251.101277   24660.0  557360.00  602387.0
M          AD           134234.000116  220159.0  535693.75  593544.0
           non-AD       189411.138563   78030.0  506101.00  585048.0


                              75%       max
PatientSex Diagnóstico
F          AD           659712.25  755759.0
           non-AD       668200.25  760661.0
M          AD           661646.75  749694.0
           non-AD       625034.00  700225.0

[4 rows x 40 columns]

In [13]:
test.groupby('Diagnóstico').describe()

            Unnamed: 0.2                                                       \
                   count        mean        std    min     25%    50%     75%
Diagnóstico
AD                  34.0  167.647059  96.861001    6.0   90.25  145.5  252.75
non-AD              29.0  497.827586  85.831258  348.0  430.00  521.0  564.00

                   Unnamed: 0.1              ...    StudyDate              \
               max        count        mean  ...          75%         max
Diagnóstico                                  ...
AD           322.0         34.0  167.647059  ...  20200860.25  20221031.0
non-AD       633.0         29.0  497.827586  ...  20190322.00  20220811.0

            PatientID                                                   \
                count           mean            std      min       25%
Diagnóstico
AD               34.0  517336.264706  228460.538399   7895.0  504666.0
non-AD           29.0  508399.689655  187963.676825  75457.0  461144.0


                  50%       75%       max
Diagnóstico
AD           576280.5  667702.0  765151.0
non-AD       555477.0  611927.0  766586.0

[2 rows x 40 columns]

In [19]:
test.groupby(['PatientSex', 'Diagnóstico']).describe()

                       Unnamed: 0.2                                        \
                              count        mean         std    min    25%
PatientSex Diagnóstico
F          AD                  21.0  156.523810   93.043333    6.0  109.0
           non-AD              14.0  474.642857   73.331290  348.0  416.5
M          AD                  13.0  185.615385  103.951542   46.0   84.0
           non-AD              15.0  519.466667   93.281346  358.0  472.5

                                             Unnamed: 0.1              ...  \
                          50%     75%    max        count        mean  ...
PatientSex Diagnóstico                                                 ...
F          AD           142.0  224.00  318.0         21.0  156.523810  ...
           non-AD       495.0  526.75  579.0         14.0  474.642857  ...
M          AD           201.0  276.00  322.0         13.0  185.615385  ...
           non-AD       532.0  589.50  633.0         15.0  519.466667  ...

                          StudyDate             PatientID                 \
                                75%         max     count           mean
PatientSex Diagnóstico
F          AD           20191112.00  20220811.0      21.0  491018.476190
           non-AD       20171162.75  20220811.0      14.0  535927.500000
M          AD           20210831.00  20221031.0      13.0  559849.615385
           non-AD       20190366.50  20210924.0      15.0  482707.066667

                                                                      \
                                  std       min        25%       50%
PatientSex Diagnóstico
F          AD           238993.352338    7895.0  471516.00  556188.0
           non-AD       175331.328846   75457.0  535721.75  554492.0
M          AD           212526.778919  113929.0  538318.00  591117.0
           non-AD       201619.348783  127385.0  360878.50  569223.0


                              75%       max
PatientSex Diagnóstico
F          AD           642017.00  765151.0
           non-AD       610660.75  766586.0
M          AD           733054.00  763634.0
           non-AD       605573.00  725218.0

[4 rows x 40 columns]

In [23]:
train.to_csv(outputTrainFile)
val.to_csv(outputValFile)
test.to_csv(outputTestFile)